### PR TITLE
land: fix consumer ir blaster

### PR DESCRIPTION
**Pull request by frapeti**

### CODE REVIEW

**Comment by zwliew** [comment]
hey frapeti, long time no see :D you got a redmi 3s too?

**Comment by Anik1199** [comment]
This fixed IR Blaster on my Redmi 3 as well :)

**Comment by frapeti** [comment]
yep 😋

**Comment by zwliew** [comment]
I'm not working on CM 14.1 until we get a kernel source release. This branch is only meant for successfully syncing the tree in CM 14.1.

I'll push the entire CM 13.0 branch up to CM 14.1 when I start working on CM 14.1.

**Pull request closed without merging**
