### PR TITLE
Fix some issues.

### PR DESCRIPTION
**Pull request by HridayHS**

### CODE REVIEW

**Comment by zwliew** [comment]
Please identify what issues these fix.

**Comment by zwliew** [comment]
Also, I wonder if you actually tested this? (since a few hours back you haven't even unlocked your device)

**Comment by HridayHS** [comment]
Now tested.
This commit 1. https://github.com/zwliew/android_device_xiaomi_land/pull/5/commits/e6d45798b4b76cbaf1f60d6c0fae948bab5ef360 also requires https://github.com/zwliew/proprietary_vendor_xiaomi/pull/1/commits/c8ec2ce203d84a351c39a624ba8b25561592e8fb to fix low volume of audio output of device.

2. This commit land: Disable wpa and p2p supplicant debug: https://github.com/zwliew/android_device_xiaomi_land/pull/5/commits/e7fb53936a3f69416842e59fd056d63c995f6517 will disable debugging, as per now WiFI is working so, we don't need to debug it and get extra things for WiFi in logs.

3. RIL is working fine now and we don't need spam in logcat: land: Stop the QC-QMI message spam: https://github.com/zwliew/android_device_xiaomi_land/pull/5/commits/c3c82911d4a13e4362b23d8d7b0bb93a065751f0

4. land: Enable WiFi display: WiFI display is enabled by stock, tested and working fine.

For other commit there is commit message and I know you understand what all this commit is for but still as a learning part I mentioned everything as per me it is. :)

**Comment by fedosis** [comment]
Also i think decreasing number of always-active big cores from 2 to 0 needed.
In init.qcom.power.rc
# Core control
    write /sys/devices/system/cpu/cpu0/core_ctl/min_cpus 0

**Comment by HridayHS** [comment]
Update: Set default name for Hotspot and Wi-Fi direct as per stock. https://github.com/zwliew/android_device_xiaomi_land/pull/5/commits/e8260b5399dbe7b399152106b65db14ee750a2e5

**Comment by zwliew** [comment]
What kind of issue is being fixed by https://github.com/zwliew/android_device_xiaomi_land/pull/5/commits/9e8a774eed0d9cc9a4b40543b9ce6c760023f163?

**Pull request closed without merging**
